### ISSUE TITLE
[Repositorios] Dividir los repos

### ISSUE THREAD

**Issue by leandro-gomez** [DesarrolloDeAplicaciones-GrupoA/DesarrolloDeAplicaciones-GrupoA#6]
Si bien este es un tema que ya hablamos, me gustaria revivirlo.

Me gustaria hacer dos repositorios, cada uno con el nombre de los subdirectorios del proyecto, i.e., "desapp-groupA-backend" y "desapp-groupA-frontend" o hacer subproyectos.

Esto nos traeria los siguientes beneficios:
## Integraciones:
- al configurar travis, no sera necesario hacer un "cd desapp-groupA-backend".
- Sera posible configurar travis para que testee el frontend.
- codacy podra dar mejores metricas si cada repo esta separado
- Sera posible hacer un deploy a Heroku en simples pasos
- Si un miembro trabaja en el backend, el que trabaje en el frontend no tendra problemas de merge/rebase, etc.

Que les parece @damianlattenero @loiaconopablo ?

**Comment by damian-rafael-lattenero** [comment]
Por mí está bien.

**Comment by loiaconopablo** [comment]
Si, dale. No tengo problema. 
Saludos
El 7/4/2016 11:52 p. m., Leandro Julian notifications@github.com escribió:Si bien este es un tema que ya hablamos, me gustaria revivirlo.

Me gustaria hacer dos repositorios, cada uno con el nombre de los subdirectorios del proyecto, i.e., "desapp-groupA-backend" y "desapp-groupA-frontend" o hacer subproyectos.

Esto nos traeria los siguientes beneficios:

##Integraciones:

al configurar travis, no sera necesario hacer un "cd desapp-groupA-backend".Sera posible configurar travis para que testee el frontend.codacy podra dar mejores metricas si cada repo esta separadoSera posible hacer un deploy a Heroku en simples pasosSi un miembro trabaja en el backend, el que trabaje en el frontend no tendra problemas de merge/rebase, etc.

Que les parece @damianlattenero @loiaconopablo ?
